export enum EditablePageComponentSlugs {
  BANNER = 'banner',
  INTRO_BLOCK = 'intro-block',
  TEXT_BLOCK_AND_SLIDESHOW = 'text-block-slideshow',
  TEXT_WITH_3_BLOCK_IMAGES = 'title-with-3-block-images',
  SLIDESHOW_BLOCK = 'slideshow',
  SPECIAL_OFFERS_SLIDESHOW = 'text_block_with_special_offers_slideshow',
  PIC_LEFT = 'pic-left',
  BANNER_QUALITIES = 'banner-qualities',
  EXPERIENCES_LIST = 'experiences-list',
  CONTACT_FORM = 'contact-form',
  SELLING_POINTS = 'text_block_and_selling_points',
  ADVANTAGES = 'advantages',
  JOURNEY_SLIDER = 'our-journey',
  EXTRA_SERVICES = 'extra-services',
  TESTIMONIALS = 'testimonials',
  FAQS = 'faqs',
  INLINE_TITLE_WITH_BUTTON = 'inline-title-with-button',
  PROPERTY_MAP = 'location',
  DESTINATION_COMMUNITIES = 'destination_communities',
  SECTION_SEPARATOR = 'section_separator',
}
