import { SlideProps } from '~/components/Sliders/SliderManager/types';

export const destinationCards: SlideProps[] = [
  {
    title: 'Punt de Mita Aera',
    caption: 'Mexico',
    description: '',
    cta_url: '#',
    image: '/punta-mita-low-res.png',
    cta_text: '',
    extra_data: '',
    mobile_image: '',
    alt_text_desktop: '',
    alt_text_mobile: '',
  },
  {
    title: 'Los Cabos',
    caption: 'Mexico',
    description: '',
    cta_url: '#',
    image: '/los_cabos.png',
    cta_text: '',
    extra_data: '',
    mobile_image: '',
    alt_text_desktop: '',
    alt_text_mobile: '',
  },
  {
    title: 'Barbados',
    caption: 'Barbados',
    description: '',
    cta_url: '#',
    image: '/barbados.png',
    cta_text: '',
    extra_data: '',
    mobile_image: '',
    alt_text_desktop: '',
    alt_text_mobile: '',
  },
  {
    title: 'Barbados',
    caption: 'Barbados',
    description: '',
    cta_url: '#',
    image: '/barbados.png',
    cta_text: '',
    extra_data: '',
    mobile_image: '',
    alt_text_desktop: '',
    alt_text_mobile: '',
  },
];
