import { SlideProps } from '~/components/Sliders/SliderManager/types';

export const experiencesSlides: SlideProps[] = [
  {
    title: 'Golf',
    caption: '',
    description: '',
    cta_url: '#',
    image: '/image5.png',
    cta_text: '',
    extra_data: '',
    mobile_image: '',
    alt_text_desktop: '',
    alt_text_mobile: '',
  },
  {
    title: 'Beach Clubs',
    caption: '',
    description: '',
    cta_url: '#',
    image: '/image6.png',
    cta_text: '',
    extra_data: '',
    mobile_image: '',
    alt_text_desktop: '',
    alt_text_mobile: '',
  },
  {
    title: 'Spa',
    caption: '',
    description: '',
    cta_url: '#',
    image: '/image7.png',
    cta_text: '',
    extra_data: '',
    mobile_image: '',
    alt_text_desktop: '',
    alt_text_mobile: '',
  },
  {
    title: 'Tennis',
    caption: '',
    description: '',
    cta_url: '#',
    image: '/image8.png',
    cta_text: '',
    extra_data: '',
    mobile_image: '',
    alt_text_desktop: '',
    alt_text_mobile: '',
  },
];
